development:
  adapter: postgresql
  encoding: utf8
  database: sweatwork_development
  pool: 5
  host: localhost
  username: 
  password: 
  port: 5432


development:
  adapter: postgresql
  encoding: utf8
  database: sweatwork_test
  pool: 5
  host: localhost
  username: 
  password: 
  port: 5432